---
- name: LEMP Stack Setup
  hosts: all
  remote_user: admin
  become: yes

  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: upgrade all packages
    apt: upgrade=dist force_apt_get=yes

  - name: set timezone
    command: timedatectl set-timezone Africa/Lagos

  - name: Install Apache
    apt:
      name: apache2
      state: latest

  - name: Output hostname 
    shell: echo $(hostname) > /var/www/html/index.html

  - name: Restart apache
    service:
      name: apache2
      state: restarted
