---
- name: LEMP Stack Setup
  hosts: all
  remote_user: admin
  become: yes

  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: upgrade all packages
    apt: upgrade=dist force_apt_get=yes

  - name: set timezone
    command: timedatectl set-timezone Africa/Lagos

  - name: Install Apache
    apt:
      name: apache2
      state: latest

  - name: Install PHP
    apt:
      name: php
      state: latest

  - name: Create a PHP file from a template
    template:
    src: templates/info.php.j2
    dest: /var/www/html/info.php

  - name: Remove default index.html file
    file:
    path: /var/www/html/index.html
    state: absent

  - name: Restart apache
    service:
    name: apache2
    state: restarted
