---
- include_vars: templates/vars.yaml

- name: Install PHP 7.4 & dependency
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - php
  - php-fpm
  - php-curl
  - php-cli
  - php-zip
  - php-mysql
  - php-xml

- name: create a directory for php
  file:
    path: /var/www/html
    state: directory
    mode: 0755

- name: create folder and index.php to display server name
  template:
    src: templates/index.php.j2
    dest: /var/www/html/index.php
  tags: index
